### ISSUE TITLE
Bug - Both User and Computer picked same, but score is not tie

### ISSUE THREAD

**Issue by JatinBehlCarrot** [shreyasachdeva123/rock-paper-scissors#1]
Check image.
When user picked paper (red highlight shown), and the UI shows that the computer also picked paper (red highlight shown), the score is not showing as tie but as "Oops! You lose this chance. "

![image](https://user-images.githubusercontent.com/71669969/115264157-0b82e180-a104-11eb-854a-8e9ba6b9f2db.png)

Expected results:
When computer and user picked the same, the score should be tie.

**Comment by JatinBehlCarrot** [comment]
@shreyasachdeva123 ⬆️

**Comment by shreyasachdeva123** [comment]
The bug has been fixed.
